# python main.py -T "senolytics"
# python main.py -T "senolysis"
# python main.py -T "CAR-T"
# python main.py -T "CAR-T x senolysis"
# python main.py -T "Eliminate senescent cells"
# python main.py -T "Oncology"
# python main.py -T "Antibody drug discovery"
# python main.py -T "Antibody drug conjugate"
# python main.py -T "Antibody drug discovery x AI simulation"
# python main.py -T "Strengthen antibody drug"
# python main.py -T "Smart city"
# python main.py -T "VR technology"
# python main.py -T "Spatial audio technology in VR"
# python main.py -T "VR x mindfullness"
# python main.py -T "Virtual spaces created by computers can be experienced as if they were real"

python main.py -T "AR"
python main.py -T "Smart city"